# Generated by Django 4.1 on 2022-09-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sillones',
            new_name='mesa',
        ),
        migrations.RenameModel(
            old_name='mesas',
            new_name='silla',
        ),
        migrations.RenameModel(
            old_name='sillas',
            new_name='sofa',
        ),
    ]
